[package]
name = "rust_atcoder_template"
version = "0.1.0"
authors = ["Souichi <sk.cf.msc@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = "=0.4.2"